[package]
name = "src"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
colored = "2.1.0"
git2 = { version = "0.19.0", features = ["zlib-ng-compat"] }
hex = "0.4.3"
sha1 = "0.10.6"
